"""Add agent name and description

Revision ID: 979d47d52c16
Revises: ccf39c73e9d2
Create Date: 2026-01-19 14:12:06.782323

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '979d47d52c16'
down_revision: Union[str, Sequence[str], None] = 'ccf39c73e9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TABLE agent_config ADD COLUMN IF NOT EXISTS name VARCHAR")
    op.execute("ALTER TABLE agent_config ADD COLUMN IF NOT EXISTS description TEXT")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_config', 'description')
    op.drop_column('agent_config', 'name')
    # ### end Alembic commands ###
