version: '3.8'

services:
  backend:
    build: ../backend
    container_name: backend-agente-local
    env_file:
      - ../.env
    ports:
      - "8002:8000"
    volumes:
      - ../backend:/app
    environment:
      - POSTGRES_HOST=postgres
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-admin_agente}:${POSTGRES_PASSWORD:-admin_agente_pwd_123}@postgres:5432/${POSTGRES_DB:-rag_db}
      - GUNICORN_WORKERS=${GUNICORN_WORKERS:-1}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-*}
      - PYTHONUNBUFFERED=1
      - RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_USER:-guest}:${RABBITMQ_DEFAULT_PASS:-guest}@rabbitmq:5672/

    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-agente-local
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: pgvector/pgvector:pg16
    container_name: banco-agente-local
    env_file:
      - ../.env
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres_local_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin_agente}
      - POSTGRES_DB=${POSTGRES_DB:-rag_db}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin_agente_pwd_123}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin_agente} -d ${POSTGRES_DB:-rag_db}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  worker:
    build: ../backend
    container_name: worker-agente-local
    env_file:
      - ../.env
    volumes:
      - ../backend:/app
    environment:
      - POSTGRES_HOST=postgres
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-admin_agente}:${POSTGRES_PASSWORD:-admin_agente_pwd_123}@postgres:5432/${POSTGRES_DB:-rag_db}
      - RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_USER:-guest}:${RABBITMQ_DEFAULT_PASS:-guest}@rabbitmq:5672/
      - PYTHONUNBUFFERED=1
    command: [ "sh", "/app/entrypoint.sh", "worker" ]
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      target: development
    container_name: frontend-agente-local
    env_file:
      - ../.env
    ports:
      - "5300:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8002
      - VITE_APP_API_URL=http://localhost:8002
    depends_on:
      - backend

volumes:
  postgres_local_data:
