version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: banco-agente
    env_file:
      - ../.env
    ports:
      - "${POSTGRES_PORT_EXTERNAL:-5433}:5432" # Maps host port 5433 to container port 5432 to avoid conflict with local PG
    networks:
      - network_swarm_public
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=trust # Allows passwordless connections
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  network_swarm_public:
    driver: bridge
    name: network_swarm_public
