services:

  backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend-agente-local
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - network_swarm_public
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: worker-agente-local
    command: taskiq worker src.tkq.tkq_config:broker
    env_file:
      - ../.env
    volumes:
      - ../backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - network_swarm_public
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-agente-local
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - network_swarm_public

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      target: development
    container_name: frontend-agente-local
    env_file:
      - ../.env
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
#    environment:
#      - VITE_API_URL=http://127.0.0.1:8000
    networks:
      - network_swarm_public
    depends_on:
      - backend

networks:
  network_swarm_public:
    external: true
    name: network_swarm_public
