"""Initial development schema

Revision ID: 7e67f297f63d
Revises: ddf837cb3e2e
Create Date: 2026-04-08 15:30:35.847539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '7e67f297f63d'
down_revision: Union[str, Sequence[str], None] = 'ddf837cb3e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('background_process_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('process_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_process_logs_id'), 'background_process_logs', ['id'], unique=False)
    op.create_index(op.f('ix_background_process_logs_task_id'), 'background_process_logs', ['task_id'], unique=False)
    op.create_table('global_context_variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_context_variables_id'), 'global_context_variables', ['id'], unique=False)
    op.create_index(op.f('ix_global_context_variables_key'), 'global_context_variables', ['key'], unique=True)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kb_type', sa.String(), nullable=True),
    sa.Column('question_label', sa.String(), nullable=True),
    sa.Column('answer_label', sa.String(), nullable=True),
    sa.Column('metadata_label', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_bases_id'), 'knowledge_bases', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_name'), 'knowledge_bases', ['name'], unique=True)
    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parameters_schema', sa.Text(), nullable=True),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tools_id'), 'tools', ['id'], unique=False)
    op.create_index(op.f('ix_tools_name'), 'tools', ['name'], unique=True)
    op.create_table('user_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_message', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_memory_key'), 'user_memory', ['key'], unique=False)
    op.create_index(op.f('ix_user_memory_session_id'), 'user_memory', ['session_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('agent_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('fallback_model', sa.String(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('top_p', sa.Float(), nullable=True),
    sa.Column('top_k', sa.Integer(), nullable=True),
    sa.Column('presence_penalty', sa.Float(), nullable=True),
    sa.Column('frequency_penalty', sa.Float(), nullable=True),
    sa.Column('safety_settings', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('date_awareness', sa.Boolean(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('knowledge_base', sa.Text(), nullable=True),
    sa.Column('simulated_time', sa.String(), nullable=True),
    sa.Column('rag_retrieval_count', sa.Integer(), nullable=True),
    sa.Column('rag_translation_enabled', sa.Boolean(), nullable=True),
    sa.Column('rag_multi_query_enabled', sa.Boolean(), nullable=True),
    sa.Column('rag_rerank_enabled', sa.Boolean(), nullable=True),
    sa.Column('rag_agentic_eval_enabled', sa.Boolean(), nullable=True),
    sa.Column('rag_parent_expansion_enabled', sa.Boolean(), nullable=True),
    sa.Column('security_competitor_blacklist', sa.Text(), nullable=True),
    sa.Column('security_forbidden_topics', sa.Text(), nullable=True),
    sa.Column('security_discount_policy', sa.Text(), nullable=True),
    sa.Column('security_language_complexity', sa.String(), nullable=True),
    sa.Column('security_pii_filter', sa.Boolean(), nullable=True),
    sa.Column('security_validator_ia', sa.Boolean(), nullable=True),
    sa.Column('security_bot_protection', sa.Boolean(), nullable=True),
    sa.Column('security_max_messages_per_session', sa.Integer(), nullable=True),
    sa.Column('security_semantic_threshold', sa.Float(), nullable=True),
    sa.Column('security_loop_count', sa.Integer(), nullable=True),
    sa.Column('ui_primary_color', sa.String(), nullable=True),
    sa.Column('ui_header_color', sa.String(), nullable=True),
    sa.Column('ui_chat_title', sa.String(), nullable=True),
    sa.Column('ui_welcome_message', sa.Text(), nullable=True),
    sa.Column('router_enabled', sa.Boolean(), nullable=True),
    sa.Column('router_simple_model', sa.String(), nullable=True),
    sa.Column('router_simple_fallback_model', sa.String(), nullable=True),
    sa.Column('router_complex_model', sa.String(), nullable=True),
    sa.Column('router_complex_fallback_model', sa.String(), nullable=True),
    sa.Column('inbox_capture_enabled', sa.Boolean(), nullable=True),
    sa.Column('response_translation_enabled', sa.Boolean(), nullable=True),
    sa.Column('response_translation_fallback_lang', sa.String(), nullable=True),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=True),
    sa.Column('handoff_enabled', sa.Boolean(), nullable=True),
    sa.Column('model_settings', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('metadata_val', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('source_metadata', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_items_id'), 'knowledge_items', ['id'], unique=False)
    op.create_table('agent_knowledge_bases',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_config.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'knowledge_base_id')
    )
    op.create_table('agent_tools',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_config.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'tool_id')
    )
    op.create_table('google_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_uri', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('client_secret', sa.String(), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_config.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id')
    )
    op.create_index(op.f('ix_google_tokens_id'), 'google_tokens', ['id'], unique=False)
    op.create_table('interaction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('agent_response', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('cost_brl', sa.Float(), nullable=True),
    sa.Column('handoff_to', sa.String(), nullable=True),
    sa.Column('debug_info', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_config.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_logs_id'), 'interaction_logs', ['id'], unique=False)
    op.create_index(op.f('ix_interaction_logs_session_id'), 'interaction_logs', ['session_id'], unique=False)
    op.create_table('prompt_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('version_name', sa.String(), nullable=True),
    sa.Column('character_count', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_config.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_drafts_id'), 'prompt_drafts', ['id'], unique=False)
    op.create_table('session_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('cost_brl', sa.Float(), nullable=True),
    sa.Column('is_test_session', sa.Boolean(), nullable=True),
    sa.Column('test_report', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_config.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_summaries_id'), 'session_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_session_summaries_session_id'), 'session_summaries', ['session_id'], unique=True)
    op.create_table('support_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_config.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unanswered_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_config.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unanswered_questions_id'), 'unanswered_questions', ['id'], unique=False)
    op.create_index(op.f('ix_unanswered_questions_session_id'), 'unanswered_questions', ['session_id'], unique=False)
    op.create_table('feedback_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interaction_log_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('original_response', sa.Text(), nullable=True),
    sa.Column('corrected_response', sa.Text(), nullable=True),
    sa.Column('system_prompt_snapshot', sa.Text(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('correction_note', sa.Text(), nullable=True),
    sa.Column('exported_to_finetune', sa.Boolean(), nullable=True),
    sa.Column('finetune_job_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_config.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interaction_log_id'], ['interaction_logs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_logs_id'), 'feedback_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_logs_id'), table_name='feedback_logs')
    op.drop_table('feedback_logs')
    op.drop_index(op.f('ix_unanswered_questions_session_id'), table_name='unanswered_questions')
    op.drop_index(op.f('ix_unanswered_questions_id'), table_name='unanswered_questions')
    op.drop_table('unanswered_questions')
    op.drop_table('support_requests')
    op.drop_index(op.f('ix_session_summaries_session_id'), table_name='session_summaries')
    op.drop_index(op.f('ix_session_summaries_id'), table_name='session_summaries')
    op.drop_table('session_summaries')
    op.drop_index(op.f('ix_prompt_drafts_id'), table_name='prompt_drafts')
    op.drop_table('prompt_drafts')
    op.drop_index(op.f('ix_interaction_logs_session_id'), table_name='interaction_logs')
    op.drop_index(op.f('ix_interaction_logs_id'), table_name='interaction_logs')
    op.drop_table('interaction_logs')
    op.drop_index(op.f('ix_google_tokens_id'), table_name='google_tokens')
    op.drop_table('google_tokens')
    op.drop_table('agent_tools')
    op.drop_table('agent_knowledge_bases')
    op.drop_index(op.f('ix_knowledge_items_id'), table_name='knowledge_items')
    op.drop_table('knowledge_items')
    op.drop_table('agent_config')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_memory_session_id'), table_name='user_memory')
    op.drop_index(op.f('ix_user_memory_key'), table_name='user_memory')
    op.drop_table('user_memory')
    op.drop_index(op.f('ix_tools_name'), table_name='tools')
    op.drop_index(op.f('ix_tools_id'), table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_knowledge_bases_name'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_id'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index(op.f('ix_global_context_variables_key'), table_name='global_context_variables')
    op.drop_index(op.f('ix_global_context_variables_id'), table_name='global_context_variables')
    op.drop_table('global_context_variables')
    op.drop_index(op.f('ix_background_process_logs_task_id'), table_name='background_process_logs')
    op.drop_index(op.f('ix_background_process_logs_id'), table_name='background_process_logs')
    op.drop_table('background_process_logs')
    # ### end Alembic commands ###
