"""Add fallback_model, temperature and top_p to agent_config

Revision ID: ccf39c73e9d2
Revises: 
Create Date: 2026-01-19 11:39:26.218098

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ccf39c73e9d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TABLE agent_config ADD COLUMN IF NOT EXISTS fallback_model VARCHAR")
    op.execute("ALTER TABLE agent_config ADD COLUMN IF NOT EXISTS temperature FLOAT")
    op.execute("ALTER TABLE agent_config ADD COLUMN IF NOT EXISTS top_p FLOAT")
    op.execute("CREATE INDEX IF NOT EXISTS ix_interaction_logs_session_id ON interaction_logs (session_id)")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interaction_logs_session_id'), table_name='interaction_logs')
    op.drop_column('agent_config', 'top_p')
    op.drop_column('agent_config', 'temperature')
    op.drop_column('agent_config', 'fallback_model')
    # ### end Alembic commands ###
